site_name: "Pavel Usanli"
site_url: "https://pavel-usanli.online/new/"

theme:
  name: material
  language: en
  font:
    text: Poppins
  palette:
    # Light mode
    - scheme: default
      primary: grey
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: grey
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md

markdown_extensions:
  - attr_list

extra_css:
  - assets/main.css

plugins:
  - search
  - pdf-export:
      combined: true
      combined_output_path: assets/pavel-usanli-resume.pdf
      enabled_if_env: ENABLE_PDF_EXPORT

extra:
  analytics:
    provider: google
    property: G-2N4KSCDHF1
